---
resources:
- name: resource-tutorial
  type: git
  source:
    uri: https://github.com/starkandwayne/concourse-tutorial.git
- name: resource-app
  type: git
  source:
    uri: https://github.com/pdesrochers01/simple-go-web-app.git

- name: resource-deploy-web-app
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: paul.desrochers@multiforce.com
    password: Breakeven1!
    organization: Multiforce
    space: prod
    skip_cert_check: true

jobs:
- name: job-test-app
  public: true
  plan:
  - get: resource-tutorial
  - get: resource-app
    trigger: true
  - task: web-app-tests
    file: resource-tutorial/10_job_inputs/task_run_tests.yml
- name: job-deploy-app
  serial: true
  plan:
  - get: resource-app
    trigger: true
    passed: 
      - job-test-app
  - put: resource-deploy-web-app
    params:
      manifest: resource-app/manifest.yml
      path: resource-app