---
resources:
- name: resource-tutorial
  type: git
  source:
    uri: https://github.com/starkandwayne/concourse-tutorial.git
- name: resource-app
  type: git
  source:
    uri: https://github.com/pdesrochers01/simple-go-web-app.git

- name: resource-deploy-web-app-prod
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: paul.desrochers@multiforce.com
    password: Breakeven1!
    organization: Multiforce
    space: prod
    skip_cert_check: true
- name: resource-deploy-web-app
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: paul.desrochers@multiforce.com
    password: Breakeven1!
    organization: Multiforce
    space: QC
    skip_cert_check: true

jobs:
- name: Unit-testing
  public: true
  plan:
  - get: resource-tutorial
  - get: resource-app
    trigger: true
  - task: web-app-tests
    file: resource-tutorial/10_job_inputs/task_run_tests.yml
- name: job-deploy-app
  serial: true
  plan:
  - get: resource-app
    trigger: true
    passed: 
      - Unit-testing
  - put: resource-deploy-web-app
    params:
      manifest: resource-app/manifest.yml
      path: resource-app
      current_app_name: simple-go-web-app
- name: load-test
  public: true
  plan:
  - get: resource-app
    trigger: true
    passed:
      - job-deploy-app
  - task: load-test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      run:
        path: echo
        args: ["Hello, world!"]
- name: job-deploy-prod
  serial: true
  plan:
  - get: resource-app
    trigger: true
    passed: 
      - load-test
  - put: resource-deploy-web-app-prod
    params:
      manifest: resource-app/manifest.yml
      path: resource-app
      current_app_name: simple-go-web-app